# Generated by Django 6.0.1 on 2026-01-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.CharField(default='Test Value', max_length=50),
        ),
    ]
