# Generated by Django 6.0.1 on 2026-01-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test',
        ),
    ]
