# Generated by Django 6.0.1 on 2026-01-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(default='default.pdf', upload_to=''),
        ),
    ]
