# Generated by Django 6.0.1 on 2026-01-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student2_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student2',
            new_name='Student',
        ),
    ]
