# Generated by Django 6.0.1 on 2026-01-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
