# Generated by Django 6.0.1 on 2026-01-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
