# Generated by Django 6.0.1 on 2026-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
    ]
