# Generated by Django 6.0.1 on 2026-01-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_car2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Car2',
        ),
    ]
