# Generated by Django 6.0.1 on 2026-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
