# Generated by Django 6.0.3 on 2026-04-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='MyOXdaiApDaaFgAnmK9raRO6u08lEKwP', editable=False, max_length=32, unique=True),
        ),
    ]
