# Generated by Django 6.0.1 on 2026-01-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipe2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe2',
            name='image',
        ),
    ]
