# Generated by Django 6.0.1 on 2026-01-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_remove_recipe2_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe2',
        ),
    ]
