# Generated by Django 6.0.1 on 2026-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_delete_recipe2'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
