# Generated by Django 6.0.1 on 2026-01-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
