# Generated by Django 6.0.1 on 2026-02-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
