GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNjE1ODUxLCJpYXQiOjE3NzE2MTU1NTEsImp0aSI6ImJjZTA5Zjc1ZGRmODRjMzRiMjEzN2FiMDRmNWM5NzM1IiwidXNlcl9pZCI6IjIifQ.i3LVdRMs0pj4y__0VB2OwK87f2aC4mlzjkfhkyEOTc0

{
    "name": "Why Isn't The Login Function Working?",
    "description": "This God Damn HTTP BS Isn't Accepting The New User I Created And It's Really Irking Me Because, Well, There's No Reason It Shouldn't Work.",
    "price": 420.69,
    "stock": 2
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

GET http://localhost:8000/orders/user-orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMTMxNzM4LCJpYXQiOjE3NzIxMzE0MzgsImp0aSI6IjJmYzE2MzY2Mzg4MDQ4ODhhZjU0ODAzZmJjYzJjMGQ5IiwidXNlcl9pZCI6IjEifQ.uCHAOvsx0LUWjtdkBZqRpjwk2pX6GEmuJh6dajfeGns

{
    "username": "admin",
    "password": "test"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "token here"
}

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzAyNDU4LCJpYXQiOjE3NzIzMDIxNTgsImp0aSI6IjRlZWY5OGI3YTM4MDQwZmFiZDY3OGEyYmU2MmY1MzEyIiwidXNlcl9pZCI6IjEifQ.IY8EzXhln0W7I9xgJNx87RbA5j0VQn7T92wLFfsz5gM

{
    "name": "A Better Coffee Machine",
    "description": "This Coffee Machine Is So Much Better Than The Last One. It Makes Better Coffee, It Looks Better, And It Has A Longer Cord. It's Just Better.",
    "price": 69.99,
    "stock": 5
}

###

DELETE http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/orders/6e4a7c10-bdfd-48b0-ad32-1b6b3c1a7cc9/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzAzMjk5LCJpYXQiOjE3NzIzMDI5OTksImp0aSI6IjA5YjE4NTRlMDQ3ODQyYzdhMDEzM2JjNTEyNTNkMTI3IiwidXNlcl9pZCI6IjEifQ.v4BVmteWR13LpxMJYTEAu6Dd6Pa4mMiZCePvyJG7KIA

{
	"status": "Pending",
	"items": [
		{
				"product": 4,
				"quantity": 2
		},
		{
				"product": 3,
				"quantity": 3
		}
	]	
}

###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzAzNjA5LCJpYXQiOjE3NzIzMDMzMDksImp0aSI6IjdhZjgxMTVhYzQwNTRmYjRhZmJhOTgwZjlkZjM5ZWFkIiwidXNlcl9pZCI6IjEifQ.Bs7CNan3xOrhLMHl6Zr1dgBf-kVCfPxlIPf67pL5A_4


{
	"status": "Pending",
	"items": [
		{
				"product": 6,
				"quantity": 3
		},
		{
				"product": 5,
				"quantity": 3
		}
	]	
}

###

DELETE http://localhost:8000/orders/c9981293-f562-4d9f-83e1-f5385013ece0/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMzAzNjA5LCJpYXQiOjE3NzIzMDMzMDksImp0aSI6IjdhZjgxMTVhYzQwNTRmYjRhZmJhOTgwZjlkZjM5ZWFkIiwidXNlcl9pZCI6IjEifQ.Bs7CNan3xOrhLMHl6Zr1dgBf-kVCfPxlIPf67pL5A_4